name: plasmabio-template-octave
# channels priority
# conda-forge has highest priority
channels:
  - defaults
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Octave environment
  # https://github.com/Calysto/octave_kernel/
  - gnuplot
  - octave
  - octave_kernel
  - texinfo
  - cxx-compiler
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive