name: plasmabio-template-octave
# channels priority
# conda-forge has highest priority
channels:
  - defaults
  - hcc
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Octave environment
  # https://github.com/Calysto/octave_kernel/
  - gnuplot
  - octave
  - octave_kernel
  - texinfo
  # https://anaconda.org/hcc/octave-io
  - octave-io
  # https://anaconda.org/hcc/octave-struct
  - octave-struct
  # https://anaconda.org/hcc/octave-image
  - octave-image
  # https://anaconda.org/hcc/octave-control
  - octave-control
  # https://anaconda.org/hcc/octave-statistics
  - octave-statistics
  # https://anaconda.org/hcc/octave-optim
  - octave-optim
  # https://anaconda.org/hcc/octave-control
  - octave-control
  # https://anaconda.org/hcc/octave-signal
  - octave-signal
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive

